//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Notes { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int PatientId { get; set; }
        public int StaffId { get; set; }
        public int XRayRoomId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff BookerStaff { get; set; }
        public virtual XRayRoom XRayRoom { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
