//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Ratings = new HashSet<Rating>();
        }

        public int Id { get; set; }
        [DisplayName("Session")]
        public System.DateTime DateTime { get; set; }
        public string Notes { get; set; }
        public bool IsCompleted { get; set; }
        [DisplayName("Created on")]
        public System.DateTime DateCreated { get; set; }
        public int PatientId { get; set; }
        public int StaffId { get; set; }
        public int XRayRoomId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
        [DisplayName("X-Ray Room")]
        public virtual XRayRoom XRayRoom { get; set; }
    }
}