//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public short Value { get; set; }
        public string Comment { get; set; }
        public int MedicalCenterId { get; set; }
        public int PatientId { get; set; }
    
        public virtual MedicalCenter MedicalCenter { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
