//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Rating
    {
        public int Id { get; set; }
        [Required]
        [Range(1, 5, ErrorMessage = "Rating must be between 1 and 5")]
        public short Value { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "Comment must be less than 500 characters.")]
        [AllowHtml]
        public string Comment { get; set; }
        public int MedicalCenterId { get; set; }
        public int PatientId { get; set; }
        public int Booking_Id { get; set; }

        public virtual Booking Booking { get; set; }
        [DisplayName("Medical Center")]
        public virtual MedicalCenter MedicalCenter { get; set; }
        public virtual Patient Patient { get; set; }
    }
}