//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    
    public enum Role : short
    {
        Admin = 0,
        FacilityManager = 1,
        MedicalStaff = 2,
        Standard = 3
    }
}
