//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    [DisplayName("X-Ray Room")]
    public partial class XRayRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XRayRoom()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        [DisplayName("Room Number")]
        public string RoomNumber { get; set; }
        public int MedicalCenterId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual MedicalCenter MedicalCenter { get; set; }
    }
}
